# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json
site_name: The Book of BDK
repo_name: bitcoindevkit/bdk
repo_url: https://github.com/bitcoindevkit/bdk
plugins:
  - search

theme:
  name: material
  logo: assets/logo.png
  icon:
    repo: fontawesome/brands/github
  favicon: assets/favicon.ico
  palette:
    - scheme: default
      primary: white
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: black
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.instant
    # - navigation.indexes
    - navigation.footer
    - navigation.expand
    - search.suggest
    - search.highlight

extra:
  homepage: https://bitcoindevkit.org
  generator: false
  social:
    - icon: fontawesome/solid/globe
      link: https://bitcoindevkit.org
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/bitcoindevkit
    - icon: fontawesome/brands/discord
      link: https://discord.gg/dstn4dQ

markdown_extensions:
  - tables
  - attr_list
  - pymdownx.highlight:
      anchor_linenums: true
      linenums: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji  
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - def_list

nav:
  - Getting Started: 
    - About: index.md
    - Project Organization: getting-started/organization.md
    - Getting Started: getting-started/getting-started.md
    - Companion Codebase: getting-started/companion-code.md
  - Cookbook:
    - BDK Wallet:
      - Electrum: cookbook/wallet/electrum.md
      - Esplora: cookbook/wallet/esplora.md
      - RPC: cookbook/wallet/rpc.md
    - Keys and Descriptors:
      - Working with Descriptors: cookbook/descriptors.md
  - Architecture:
    - Overview:
      - Design: architecture/design.md
